.template-project: &project
  project: devops/auto-devops
  ref: master

include:
  - file: auto-devops.yml
    << : *project
  - file: reactjs.gitlab-ci.yml
    << : *project
  - file: docker.gitlab-ci.yml
    << : *project
  - file: helm.gitlab-ci.yml
    << : *project
