version: "3"

services:
  konoha:
    image: "476234812167.dkr.ecr.ap-southeast-1.amazonaws.com/konoha-dev:latest"
    ports:
      - 5000:5000
    networks:
      - node-app
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

networks:
  node-app:
    driver: bridge
