export const Services = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  POST_SERVICE: 'POST_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  FILE_SERVICE: 'FILE_SERVICE',
}

export const MessageQueueEvents = {
  POST_CREATED: 'POST_CREATED',
}