module.exports = {
	AUTH: {
		REGISTER_SUCCESS: 'REGISTER_SUCCESS',
		LOGIN_SUCCESS: 'LOGIN_SUCCESS',
		LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
		TOKEN_REFRESHED: 'TOKEN_REFRESHED',
		EMAIL_EXISTED: 'EMAIL_EXISTED',
		EMAIL_NOT_EXISTED: 'EMAIL_NOT_EXISTED',
		USERNAME_EXISTED: 'USERNAME_EXISTED',
		PASSWORD_EXEEDED: 'PASSWORD_EXEEDED',
		PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
		SESSION_EXPIRED: 'SESSION_EXPIRED',
		UNAUTHENTICATED: 'UNAUTHENTICATED'
	},
	USER: {
		USER_NOT_FOUND: 'USER_NOT_FOUND',
	},
	POST: {
		POST_NOT_FOUND: 'POST_NOT_FOUND',
		POST_LIKED: 'POST_LIKED',
		POST_SAVED: 'POST_SAVED'
	},
	FILE: {
		FILE_MISSED: 'FILE_MISSED',
	},
	COMMENT: {
		COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
		COMMENT_LIKED: 'COMMENT_LIKED'
	},
}